apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-information
  namespace: weavek8sops
spec:
  encryptedData:
    password: AgB1pvm+OJYQu8Fi8zN5hMreyn+8jx/avQjU8OGZtGLESn5NRvpnbbyVnBI5ZzZVwRDk6EOFPC8zKTvaYOwj1I6hvCsD1bSXez+M8AI6vmwcIamKQg28D4c0nnwhhJczFFKP/WUhiOQl74RcnHQnhObnkXaNmKqxkcR1EE1o3UuwlrGx8z4vxnoqScdPe+67KxS/3SWudgG1jkWXyJPBN3vhTS2J0Yxb6Y7C7V/Y5qMO3Rl8n1CsvVJNxa2eABssoTw183vlUsZxkFVeeyQu2PirkI6/eIFGgGhrS0Rn4XhjZ+2MbdYxExlfXul9u+FuYzstjIr0UpXBUGyV2C6QS/VDK5Ov3mWC30HC35v62FBw8dl0BRClDthdjS9WT57JVB/iYKa+vTs30KmWYQKpOrsg6K1OwhVQatNmVZjcBPlDZtFyub7mF5snudl5qgtF6TePyHRQqHCuE2xiegdFv5icIOEWiRNwqxQwaYsOMz9NBZKR9D8Ss5Nbi+9fyAShJk5P1fxwLiZVNuI0p5yXPRGwmaveQbb6PQvLCAoo3djXFlHEWUPGNSrb4SHYHNq5c4xcbJ2qDBpNbFreVmWwf6QShOIcDti3SG/xZiSz+smmwH6IslTCpZfHyZjoh/BRZzOI+GNIO3czI01XQjw0Y8L5CKEiHHck4AcBAJs2tX/Y2rO65oIEuoaD7tOyN9/lK3jmkLbV2K65faTLpAU=
    username: AgA93aQMFHFtbd72mh6XXgPDFKKNfiWDiZzJJ/kMQlSbCfvODeT5eU4BTk2YQBtVyi/mOITAn5RvsHat6LkS1axnL9RVt8aU7xjjxMrTQm3Xxjt49jFEK+RxDeN3p56mf5xL1YnXKc8R/Msezy8gqeaFZXWbOk+6hjBj3gvsmjCbx463AF4pD9pafS1RP272upMXzWw0fnFM8CP8Xm6WDWBlKolZOaO0gA//0maGeXmlACcd3WzACNoJ6BMMemCbl28g1zl7Q8DptCIyf5D04Z/zZkq4qT82MYAtDyhUMBkZ1pwICYbquL1u/wD2HjOg5g+adf/q/PkASAlx8+zTLUKcwP3aY4bQv3wE7EAmZBViAn2ZaqcWk8XLm8n69fJ9bawoG2dGPvP7eDTHYG03ziUWvia2cgS65f+lUSfDyk1PFJzCm+WZ98Ac1l7AZRe7T/X+y8qKjddgHvw3oK75iPs9TbySK77n+9H8DxvL4xqlynrBGYJvE9eR4IDAT0CiY0cdKvaL5yGVSz/NqKCZph/bbuapZfVKI0KxWfwYOBtkWUF3DCvzJ6967sWecCVSRC5hPrcvG+NYVa4yiFSVc/tkWcz1hI+PmHpbERybvJ1AtHK+v5dClTHKE4eAa1ccLHTg9G5ttnIeFEpsZLiBrfZqrX672N4HSFljj7GBsFrW61gmX7rssMFPwMXq8KVMj0/YFLN9qz8=
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-information
      namespace: weavek8sops
    type: Opaque
status: {}

